### ISSUE TITLE
farm mgmt: Classic network monitoring

### ISSUE THREAD

**Issue by andhartl** [threefoldfoundation/tf_farmer_management_tools#3]
Kubernetes scripts for monitoring the network environment.

Purpose:  We need to provide a way to monitor the networking setup of a farmer in order to:
- provide the farmer with network uptime statistics: uptime, bandwidth available, bandwidth used
- and/or report the network uptime statistics to the minting engine to make the decision at the end of the month if the required SLA was made or breached.
-  and/or get this information from the switch/router installation of the farmer
- and/or get this information from a probe in a kubernetes cluster at the farmers farm.
-
Implementation requirements:
- configuration on router/switch?
- software monitoring on the server only?

**Comment by weynandkuijpers** [comment]
what is "the network environment"?

**Comment by andhartl** [comment]
tbd.

**Comment by m-motawea** [comment]
I think we need to configure the switches as snmp agents for some server like nagios or cacti ..,etc (classic network monitoring)

**Comment by weynandkuijpers** [comment]
Okay - I am not getting what this story is about.  I am going to attempt to write the story that this is about, please anyone that knows better to change/improve the story.  See ^^^^ we need to get that start of the story clear and defined. :pray:

**Comment by m-motawea** [comment]
https://github.com/threefoldfoundation/tf_farmer_management_tools/blob/development/docs/monitoring/readme.md
